"""empty message

Revision ID: 053df1de8fc2
Revises: 53c5246efbc6
Create Date: 2019-06-26 20:48:23.909637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '053df1de8fc2'
down_revision = '53c5246efbc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_address', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('subscriber_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_address', sa.String(length=120), nullable=False))
    op.drop_index('username', table_name='users')
    op.create_unique_constraint(None, 'users', ['email_address'])
    op.drop_column('users', 'username')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('username', 'users', ['username'], unique=True)
    op.drop_column('users', 'email_address')
    op.drop_column('users', 'active')
    op.drop_table('subscriber_type')
    op.drop_table('subcriber')
    # ### end Alembic commands ###
