"""empty message

Revision ID: 17edf1daead1
Revises: 2ad7eff35b47
Create Date: 2019-06-28 22:03:29.028942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17edf1daead1'
down_revision = '2ad7eff35b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_quote', sa.Column('content_hash', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('confirmation_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmation_code')
    op.drop_column('bot_quote', 'content_hash')
    # ### end Alembic commands ###
