"""empty message

Revision ID: 1ecad16697eb
Revises: cc20112aef4d
Create Date: 2019-09-25 21:23:45.073126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ecad16697eb'
down_revision = 'cc20112aef4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ContentItemInteraction', sa.Column('choice', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ContentItemInteraction', 'choice')
    # ### end Alembic commands ###
