"""empty message

Revision ID: 2ad7eff35b47
Revises: 61e305302fe2
Create Date: 2019-06-28 21:29:35.750260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad7eff35b47'
down_revision = '61e305302fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'chat_id')
    # ### end Alembic commands ###
