"""empty message

Revision ID: 35152c6e6d63
Revises: b8b6fc915a88
Create Date: 2019-07-10 06:54:00.546018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35152c6e6d63'
down_revision = 'b8b6fc915a88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['bot_quote.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_stats')
    # ### end Alembic commands ###
