"""empty message

Revision ID: 401cebd00f27
Revises: 5729ee63692f
Create Date: 2019-05-21 21:46:42.787467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401cebd00f27'
down_revision = '5729ee63692f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equity_price_source', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equity_price_source', 'is_active')
    # ### end Alembic commands ###
