"""empty message

Revision ID: 440edd881344
Revises: c94de65ca65a
Create Date: 2019-06-09 21:45:43.889203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440edd881344'
down_revision = 'c94de65ca65a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equity_price', sa.Column('deals_value', sa.Integer(), nullable=False))
    op.add_column('equity_price', sa.Column('downloaded_timestamp', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equity_price', 'downloaded_timestamp')
    op.drop_column('equity_price', 'deals_value')
    # ### end Alembic commands ###
