"""empty message

Revision ID: 5729ee63692f
Revises: 79dc6abaa02f
Create Date: 2019-05-21 21:40:19.169525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5729ee63692f'
down_revision = '79dc6abaa02f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equity_price_source', sa.Column('data1', sa.String(length=100), nullable=True))
    op.add_column('equity_price_source', sa.Column('data2', sa.String(length=100), nullable=True))
    op.add_column('equity_price_source', sa.Column('data3', sa.String(length=100), nullable=True))
    op.add_column('equity_price_source', sa.Column('data4', sa.String(length=100), nullable=True))
    op.add_column('equity_price_source', sa.Column('data5', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equity_price_source', 'data5')
    op.drop_column('equity_price_source', 'data4')
    op.drop_column('equity_price_source', 'data3')
    op.drop_column('equity_price_source', 'data2')
    op.drop_column('equity_price_source', 'data1')
    # ### end Alembic commands ###
