"""empty message

Revision ID: 573665663f24
Revises: 5f6741582c2b
Create Date: 2019-08-04 17:57:32.497975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573665663f24'
down_revision = '5f6741582c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['chat_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
