"""empty message

Revision ID: 5f5719125b8b
Revises: 92f5f21a262c
Create Date: 2019-05-26 19:49:25.251756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f5719125b8b'
down_revision = '92f5f21a262c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bot_quote', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('bot_quote', 'active')
    op.add_column('equity_price', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('faces', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('image_file', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('keyvalue_entry', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('keyvalue_entry', sa.Column('key_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'keyvalue_entry', 'key', ['key_id'], ['id'])
    op.drop_column('keyvalue_entry', 'name')
    op.add_column('log_self', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('messages_inbound', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('tag', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('tag', 'active')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.add_column('tag', sa.Column('active', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('tag', 'is_active')
    op.drop_column('messages_inbound', 'is_active')
    op.drop_column('log_self', 'is_active')
    op.add_column('keyvalue_entry', sa.Column('name', mysql.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'keyvalue_entry', type_='foreignkey')
    op.drop_column('keyvalue_entry', 'key_id')
    op.drop_column('keyvalue_entry', 'is_active')
    op.drop_column('image_file', 'is_active')
    op.drop_column('faces', 'is_active')
    op.drop_column('equity_price', 'is_active')
    op.add_column('bot_quote', sa.Column('active', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('bot_quote', 'is_active')
    op.drop_table('key')
    # ### end Alembic commands ###
