"""empty message

Revision ID: 5f6741582c2b
Revises: dca9d653e444
Create Date: 2019-08-04 17:53:25.842298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f6741582c2b'
down_revision = 'dca9d653e444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bot_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bot_id')
    # ### end Alembic commands ###
