"""empty message

Revision ID: 631e39c568e4
Revises: 6a965ee04048
Create Date: 2019-09-28 21:30:57.977347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631e39c568e4'
down_revision = '6a965ee04048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ContentItem', sa.Column('contentitem_id', sa.Integer(), nullable=True))
    op.add_column('ContentItem', sa.Column('contentprovider_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ContentItem', 'ContentItem', ['contentitem_id'], ['id'])
    op.create_foreign_key(None, 'ContentItem', 'ContentProvider', ['contentprovider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ContentItem', type_='foreignkey')
    op.drop_constraint(None, 'ContentItem', type_='foreignkey')
    op.drop_column('ContentItem', 'contentprovider_id')
    op.drop_column('ContentItem', 'contentitem_id')
    # ### end Alembic commands ###
