"""empty message

Revision ID: 79dc6abaa02f
Revises: a0eeeea6ef42
Create Date: 2019-05-19 14:03:39.558781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79dc6abaa02f'
down_revision = 'a0eeeea6ef42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equity_price_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name')
    )
    op.add_column('equity_price', sa.Column('equitypricesource_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'equity_price', 'equity_price_source', ['equitypricesource_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equity_price', type_='foreignkey')
    op.drop_column('equity_price', 'equitypricesource_id')
    op.drop_table('equity_price_source')
    # ### end Alembic commands ###
