"""empty message

Revision ID: 7e4406c89c09
Revises: 401cebd00f27
Create Date: 2019-05-21 22:09:03.352988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4406c89c09'
down_revision = '401cebd00f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equity_price_source', sa.Column('source_key', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'equity_price_source', ['source_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equity_price_source', type_='unique')
    op.drop_column('equity_price_source', 'source_key')
    # ### end Alembic commands ###
