"""empty message

Revision ID: 95a36f674277
Revises: 
Create Date: 2019-09-01 20:13:14.192687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95a36f674277'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_users',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('keyvalue_entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['keyvalue_entry_id'], ['keyvalue_entry.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_subscriptions')
    op.drop_table('roles_users')
    # ### end Alembic commands ###
