"""empty message

Revision ID: b4599e44dc37
Revises: a7680d6c4fb5
Create Date: 2019-05-19 13:53:04.038079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4599e44dc37'
down_revision = 'a7680d6c4fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('company_name', table_name='equity_instrument')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('company_name', 'equity_instrument', ['company_name'], unique=True)
    # ### end Alembic commands ###
