"""empty message

Revision ID: b5acfaaf5d8b
Revises: 1ecad16697eb
Create Date: 2019-09-26 21:42:15.339787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5acfaaf5d8b'
down_revision = '1ecad16697eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ContentItemInteraction', sa.Column('message_id', sa.Integer(), nullable=True))
    op.drop_column('ContentItemInteraction', 'unique_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ContentItemInteraction', sa.Column('unique_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=33), nullable=True))
    op.drop_column('ContentItemInteraction', 'message_id')
    # ### end Alembic commands ###
