"""empty message

Revision ID: b8b6fc915a88
Revises: 
Create Date: 2019-07-09 22:29:55.949199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b6fc915a88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_key_value', 'keyvalue_entry', ['key_id', 'value'])
    op.add_column('users', sa.Column('subscriptions_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscriptions_active')
    op.drop_constraint('unique_key_value', 'keyvalue_entry', type_='unique')
    # ### end Alembic commands ###
