"""empty message

Revision ID: c94de65ca65a
Revises: 5f5719125b8b
Create Date: 2019-06-09 21:22:43.101712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c94de65ca65a'
down_revision = '5f5719125b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equity_price', sa.Column('buy_offer_price', sa.Integer(), nullable=False))
    op.add_column('equity_price', sa.Column('deal_count', sa.Integer(), nullable=False))
    op.add_column('equity_price', sa.Column('from_52_week_high', sa.Integer(), nullable=False))
    op.add_column('equity_price', sa.Column('from_52_week_low', sa.Integer(), nullable=False))
    op.add_column('equity_price', sa.Column('last_sales_price', sa.Integer(), nullable=False))
    op.add_column('equity_price', sa.Column('price_move', sa.Float(precision=5), nullable=False))
    op.add_column('equity_price', sa.Column('sell_offer_price', sa.Integer(), nullable=False))
    op.add_column('equity_price', sa.Column('today_high', sa.Integer(), nullable=False))
    op.add_column('equity_price', sa.Column('today_low', sa.Integer(), nullable=False))
    op.add_column('equity_price', sa.Column('volume_count', sa.Integer(), nullable=False))
    op.drop_column('equity_price', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equity_price', sa.Column('price', mysql.FLOAT(), nullable=False))
    op.drop_column('equity_price', 'volume_count')
    op.drop_column('equity_price', 'today_low')
    op.drop_column('equity_price', 'today_high')
    op.drop_column('equity_price', 'sell_offer_price')
    op.drop_column('equity_price', 'price_move')
    op.drop_column('equity_price', 'last_sales_price')
    op.drop_column('equity_price', 'from_52_week_low')
    op.drop_column('equity_price', 'from_52_week_high')
    op.drop_column('equity_price', 'deal_count')
    op.drop_column('equity_price', 'buy_offer_price')
    # ### end Alembic commands ###
