"""empty message

Revision ID: cc20112aef4d
Revises: f01fb14bdd39
Create Date: 2019-09-25 20:22:06.952920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc20112aef4d'
down_revision = 'f01fb14bdd39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ContentItemInteraction', sa.Column('trace', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ContentItemInteraction', 'trace')
    # ### end Alembic commands ###
