"""empty message

Revision ID: f01fb14bdd39
Revises: 3d72bfdca6ed
Create Date: 2019-09-25 20:19:29.844262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01fb14bdd39'
down_revision = '3d72bfdca6ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ContentItemInteraction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('contentitem_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('unique_id', sa.String(length=33), nullable=True),
    sa.Column('data', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['contentitem_id'], ['ContentItem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ContentItemInteraction')
    # ### end Alembic commands ###
